# Generated by Django 2.2.7 on 2020-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import selling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0026_auto_20200627_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='إسم المنتج')),
                ('typeofproduct', models.CharField(max_length=150, verbose_name='نوع المنتج')),
                ('code', models.IntegerField(default=selling.models.random_string, verbose_name='كود المنتج')),
                ('description', models.TextField(verbose_name='وصف المنتج')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('update_by', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :')),
                ('price', models.FloatField(verbose_name='سعر المنتج')),
                ('count', models.FloatField(verbose_name='الكمية')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='سعر المنتج')),
            ],
            options={
                'verbose_name': 'Purchasing',
                'verbose_name_plural': 'Purchasings',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='إسم المنتج')),
                ('code', models.IntegerField(default=selling.models.random_string, verbose_name='كود المنتج')),
                ('description', models.TextField(verbose_name='وصف المنتج')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('update_by', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :')),
                ('price', models.FloatField(verbose_name='سعر المنتج')),
                ('count', models.FloatField(verbose_name='الكمية')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='هامش الربح')),
                ('typeofproducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='typeofproducts')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salarys',
            },
        ),
    ]
