# Generated by Django 2.2.7 on 2020-06-27 10:09

from django.db import migrations, models
import django.utils.timezone
import selling.models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='إسم العميل')),
                ('code', models.IntegerField(default=selling.models.random_string, verbose_name='كود العميل')),
                ('phone', models.IntegerField(verbose_name='رقم العميل')),
                ('description', models.TextField(verbose_name='وصف العميل')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('update_by', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name=' البضاعة المسحوبة حتى الأن')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.RemoveField(
            model_name='purchasing',
            name='typeofproduct',
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='description',
            field=models.TextField(verbose_name='وصف الفتورة'),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم الفتورة'),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الفتورة'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم الفتورة'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الفتورة '),
        ),
    ]
