# Generated by Django 2.2.7 on 2020-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_auto_20200627_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone1',
            field=models.IntegerField(default=1, verbose_name='رقم العميل 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.IntegerField(default=1, verbose_name='2 رقم العميل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone3',
            field=models.IntegerField(default=1, verbose_name='رقم العميل 3'),
            preserve_default=False,
        ),
    ]
