# Generated by Django 2.2.7 on 2020-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_auto_20200627_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_profit',
            field=models.FloatField(blank=True, null=True, verbose_name=' البضاعة المسحوبة حتى الأن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.IntegerField(verbose_name='رقم العميل '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.IntegerField(verbose_name='إضافة رقم ثانى'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone3',
            field=models.IntegerField(verbose_name='إضافة رقم ثالث'),
        ),
    ]
