# Generated by Django 2.2.7 on 2020-06-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_auto_20200627_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone1',
            field=models.CharField(max_length=50, verbose_name='رقم العميل '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(max_length=50, verbose_name='إضافة رقم ثانى'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone3',
            field=models.CharField(max_length=50, verbose_name='إضافة رقم ثالث'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name=' البضاعة الجديدة'),
        ),
    ]
