# Generated by Django 2.2.7 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_auto_20200627_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='phone_number',
            field=models.CharField(default=1, max_length=150, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
    ]
