# Generated by Django 2.2.7 on 2020-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0006_salary_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='order_status',
            field=models.CharField(choices=[('لم يتم التحضير', 'a'), ('يتم التحضير الأن', 'b'), ('تم التسليم', 'd'), ('تم التحضير', 'c')], default='لم يتم التحضير', max_length=150, verbose_name='حالة الفاتورة'),
        ),
    ]
