# Generated by Django 2.2.7 on 2020-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='count',
            new_name='amount_received',
        ),
        migrations.AddField(
            model_name='workers',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='المبلغ الباقي'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('إداري', 'إدارى'), ('محاسب', 'محاسب'), ('عامل', 'عامل'), ('سواق', 'سواق'), ('صنايعي', 'صنايعي')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
