# Generated by Django 2.2.7 on 2020-06-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200614_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='remaining_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='المبلغ الباقي'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('محاسب', 'محاسب'), ('صنايعي', 'صنايعي'), ('سواق', 'سواق'), ('عامل', 'عامل'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
