# Generated by Django 2.2.7 on 2020-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200614_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='Salary_discounts',
            field=models.FloatField(default=1, verbose_name='خصم من العامل '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='المبلغ الباقي'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('عامل', 'عامل'), ('إداري', 'إدارى'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
