# Generated by Django 2.2.7 on 2020-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200615_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='amount_received',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='السلف'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('سواق', 'سواق'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
