# Generated by Django 2.2.7 on 2020-06-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20200615_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='remaining_amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='المبلغ الباقي'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('محاسب', 'محاسب'), ('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
