# Generated by Django 2.2.7 on 2020-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20200615_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='المبلغ الباقي'),
        ),
    ]
