# Generated by Django 2.2.7 on 2020-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20200615_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='amount_received',
            field=models.FloatField(blank=True, null=True, verbose_name='السلف'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('إداري', 'إدارى'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('عامل', 'عامل'), ('سواق', 'سواق')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
