# Generated by Django 2.2.7 on 2020-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20200615_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('عامل', 'عامل'), ('محاسب', 'محاسب'), ('إداري', 'إدارى'), ('صنايعي', 'صنايعي')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
