# Generated by Django 2.2.7 on 2020-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_auto_20200619_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='code',
        ),
        migrations.AlterField(
            model_name='workers',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='صافي المرتب '),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('إداري', 'إدارى'), ('سواق', 'سواق')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
