# Generated by Django 2.2.7 on 2020-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_auto_20200619_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('محاسب', 'محاسب'), ('صنايعي', 'صنايعي'), ('إداري', 'إدارى'), ('عامل', 'عامل')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
