# Generated by Django 2.2.7 on 2020-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_auto_20200620_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('صنايعي', 'صنايعي'), ('إداري', 'إدارى'), ('عامل', 'عامل'), ('محاسب', 'محاسب')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
