# Generated by Django 2.2.7 on 2020-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_auto_20200620_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('إداري', 'إدارى'), ('صنايعي', 'صنايعي'), ('سواق', 'سواق'), ('عامل', 'عامل'), ('محاسب', 'محاسب')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
