# Generated by Django 2.2.7 on 2020-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_auto_20200622_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('صنايعي', 'صنايعي'), ('عامل', 'عامل'), ('سواق', 'سواق'), ('إداري', 'إدارى'), ('محاسب', 'محاسب')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
