# Generated by Django 2.2.7 on 2020-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_auto_20200624_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicing',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AddField(
            model_name='workers',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('صنايعي', 'صنايعي'), ('إداري', 'إدارى'), ('عامل', 'عامل'), ('محاسب', 'محاسب')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
