# Generated by Django 2.2.7 on 2020-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_auto_20200624_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('محاسب', 'محاسب'), ('صنايعي', 'صنايعي'), ('سواق', 'سواق'), ('عامل', 'عامل'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
