# Generated by Django 2.2.7 on 2020-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_auto_20200627_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('سواق', 'سواق'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
