# Generated by Django 2.2.7 on 2020-06-28 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_auto_20200627_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount_Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.FloatField(verbose_name='قيمة السلفة')),
                ('description', models.TextField(verbose_name='سبب السلفة')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('update_by', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :')),
            ],
            options={
                'verbose_name': 'Rmount_Received',
                'verbose_name_plural': 'Rmount_Receiveds',
            },
        ),
        migrations.AlterField(
            model_name='workers',
            name='amount_received',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Amount_Received', verbose_name='السلف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('عامل', 'عامل'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
