# Generated by Django 2.2.7 on 2020-07-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_auto_20200628_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='amount_received',
        ),
        migrations.AddField(
            model_name='amount_received',
            name='workers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Workers', verbose_name='العامل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('سواق', 'سواق'), ('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
