# Generated by Django 2.2.7 on 2020-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_auto_20200701_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='remaining_amount',
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('عامل', 'عامل'), ('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('سواق', 'سواق'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
