# Generated by Django 2.2.7 on 2020-07-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0038_auto_20200701_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount_received',
            name='remaining_amount2',
            field=models.FloatField(blank=True, null=True, verbose_name='صافي المرتب '),
        ),
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('إداري', 'إدارى'), ('سواق', 'سواق'), ('محاسب', 'محاسب'), ('عامل', 'عامل'), ('صنايعي', 'صنايعي')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
