# Generated by Django 2.2.7 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0040_auto_20200702_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('عامل', 'عامل'), ('سواق', 'سواق'), ('محاسب', 'محاسب'), ('صنايعي', 'صنايعي'), ('إداري', 'إدارى')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
