# Generated by Django 2.2.7 on 2020-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0041_auto_20200812_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='type_of_person',
            field=models.CharField(choices=[('صنايعي', 'صنايعي'), ('محاسب', 'محاسب'), ('سواق', 'سواق'), ('إداري', 'إدارى'), ('عامل', 'عامل')], default='عامل', max_length=50, verbose_name='نوع العامل'),
        ),
    ]
