# Generated by Django 2.2.7 on 2020-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='هامش الربح'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='price',
            field=models.FloatField(verbose_name='سعر المنتج'),
        ),
    ]
