# Generated by Django 2.2.7 on 2020-06-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20200614_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='description',
            field=models.TextField(verbose_name='وصف المنتج'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم المنتج'),
        ),
    ]
