# Generated by Django 2.2.7 on 2020-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_purchasing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='typeofproducts',
            field=models.CharField(max_length=150, verbose_name='نوع المنتج'),
        ),
    ]
