# Generated by Django 2.2.7 on 2020-06-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_auto_20200614_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='typeofproducts',
            new_name='typeofproduct',
        ),
    ]
