# Generated by Django 2.2.7 on 2020-06-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_auto_20200614_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasing',
            options={'verbose_name': 'Purchasing', 'verbose_name_plural': 'Purchasings'},
        ),
    ]
