# Generated by Django 2.2.7 on 2020-06-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_auto_20200615_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='هامش الربح'),
        ),
    ]
