# Generated by Django 2.2.7 on 2020-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_purchasing_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر المنتج'),
        ),
    ]
