# Generated by Django 2.2.7 on 2020-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0009_auto_20200619_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AddField(
            model_name='salary',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
    ]
