# Generated by Django 2.2.7 on 2020-06-13 14:50

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='إسم المنتج ')),
                ('code', models.IntegerField(default=products.models.random_string, verbose_name='كود المنتج')),
                ('image', models.ImageField(upload_to='Product_Image', verbose_name='صورة المنتج')),
                ('description', models.CharField(max_length=50, verbose_name='وصف المنتج')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('cost', models.FloatField(verbose_name='تكلفة المنتج')),
                ('price', models.FloatField(verbose_name='سعر المنتج')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='هامش الربح')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
