# Generated by Django 2.2.7 on 2020-06-13 14:50

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='إسم الخلطة ')),
                ('code', models.IntegerField(default=products.models.random_string, verbose_name='كود الخلطة')),
                ('image', models.ImageField(upload_to='Product_Image', verbose_name='صورة الخلطة')),
                ('type1', models.CharField(max_length=50, verbose_name='الوصفة الأولى')),
                ('type2', models.CharField(max_length=50, verbose_name='الوصفة الثانية')),
                ('type3', models.CharField(max_length=50, verbose_name='الوصفة الثالثة')),
                ('type4', models.CharField(max_length=50, verbose_name='الوصفة الرابعة')),
                ('type5', models.CharField(max_length=50, verbose_name='الوصفة الخامسة')),
                ('description', models.CharField(max_length=50, verbose_name='الوصفة بشكل عام')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'Product_Mix',
                'verbose_name_plural': 'Product_Mixs',
            },
        ),
    ]
