# Generated by Django 2.2.7 on 2020-06-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productmix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductMix', verbose_name=''),
            preserve_default=False,
        ),
    ]
