# Generated by Django 2.2.7 on 2020-06-13 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productmix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productmix',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=1, verbose_name='حجم اللفة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوصفة بشكل عام'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوصفة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوصفة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوصفة الخامسة'),
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='إسم اللفة ')),
                ('size', models.FloatField(verbose_name='وزن اللفة')),
                ('code', models.IntegerField(default=products.models.random_string, verbose_name='كود اللفة')),
                ('image', models.ImageField(upload_to='Product_Image', verbose_name='صورة اللفة')),
                ('description', models.CharField(max_length=50, verbose_name='وصف اللفة')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('cost', models.FloatField(verbose_name='تكلفة اللفة')),
                ('price', models.FloatField(verbose_name='سعر اللفة')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='هامش اللفة')),
                ('productmix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductMix', verbose_name='productmix')),
            ],
            options={
                'verbose_name': 'Roll',
                'verbose_name_plural': 'Rolls',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='roll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Roll', verbose_name='productmix'),
            preserve_default=False,
        ),
    ]
