# Generated by Django 2.2.7 on 2020-06-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200613_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='وصف المنتج'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الوصفة بشكل عام'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم الخلطة '),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(max_length=300, verbose_name='الوصفة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(max_length=300, verbose_name='الوصفة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الوصفة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الوصفة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الوصفة الخامسة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='description',
            field=models.TextField(verbose_name='وصف اللفة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم اللفة '),
        ),
        migrations.AlterField(
            model_name='roll',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='هامش الربح'),
        ),
    ]
