# Generated by Django 2.2.7 on 2020-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200614_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.FloatField(verbose_name='حجم الكيس'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='image',
            field=models.ImageField(upload_to='ProductMix_Image', verbose_name='صورة الخلطة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='image',
            field=models.ImageField(upload_to='Roll_Image', verbose_name='صورة اللفة'),
        ),
    ]
