# Generated by Django 2.2.7 on 2020-06-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200615_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='وصف المنتج'),
        ),
    ]
