# Generated by Django 2.2.7 on 2020-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200615_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Image', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductMix_Image', verbose_name='صورة الخلطة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Roll_Image', verbose_name='صورة اللفة'),
        ),
    ]
