# Generated by Django 2.2.7 on 2020-06-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200619_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMix_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='إسم الوصفة')),
                ('count', models.FloatField(verbose_name='نسبه الوصفة')),
                ('cost', models.IntegerField(verbose_name='سعر الوصفة')),
            ],
            options={
                'verbose_name': 'ProductMix_Detail',
                'verbose_name_plural': 'ProductMix_Detail',
            },
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductMix_Detail', verbose_name='الوصفة الاولى'),
        ),
    ]
