# Generated by Django 2.2.7 on 2020-06-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200620_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='products.ProductMix_Detail', verbose_name='الوصفة الاولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='products.ProductMix_Detail', verbose_name='الوصفة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type3', to='products.ProductMix_Detail', verbose_name='الوصفة الثالثة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type4', to='products.ProductMix_Detail', verbose_name='الوصفة الرابعة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type5', to='products.ProductMix_Detail', verbose_name='الوصفة الخامسة'),
            preserve_default=False,
        ),
    ]
