# Generated by Django 2.2.7 on 2020-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200620_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmix_detail',
            name='price',
            field=models.FloatField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
    ]
