# Generated by Django 2.2.7 on 2020-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200620_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmix',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
    ]
