# Generated by Django 2.2.7 on 2020-06-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productmix_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmix_detail',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='productmix_detail',
            name='count',
        ),
    ]
