# Generated by Django 2.2.7 on 2020-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200621_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='roll_price',
            field=models.FloatField(blank=True, null=True, verbose_name='السعر الكلى للفة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='price',
            field=models.FloatField(verbose_name='سعر الكيلو فى اللفة'),
        ),
    ]
