# Generated by Django 2.2.7 on 2020-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200622_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmix',
            name='type1_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخلطة'),
        ),
        migrations.AddField(
            model_name='productmix',
            name='type2_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخلطة'),
        ),
        migrations.AddField(
            model_name='productmix',
            name='type3_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخلطة'),
        ),
        migrations.AddField(
            model_name='productmix',
            name='type4_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخلطة'),
        ),
        migrations.AddField(
            model_name='productmix',
            name='type5_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix_detail',
            name='name',
            field=models.CharField(max_length=300, verbose_name='إسم المادة الخام'),
        ),
        migrations.AlterField(
            model_name='productmix_detail',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر المادة الخام'),
        ),
    ]
