# Generated by Django 2.2.7 on 2020-06-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200622_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmix',
            name='type1_price',
            field=models.IntegerField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='type2_price',
            field=models.IntegerField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='type3_price',
            field=models.IntegerField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='type4_price',
            field=models.IntegerField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmix',
            name='type5_price',
            field=models.IntegerField(default=1, verbose_name='سعر الخلطة'),
            preserve_default=False,
        ),
    ]
