# Generated by Django 2.2.7 on 2020-06-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200622_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الخلطة'),
        ),
    ]
