# Generated by Django 2.2.7 on 2020-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200622_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('ريسايكل', 'ريسايكل')], default=1, max_length=50, verbose_name='إسم الخامه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('ريسايكل', 'ريسايكل')], default=1, max_length=50, verbose_name='إسم الخامه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('ريسايكل', 'ريسايكل')], default=1, max_length=50, verbose_name='إسم الخامه'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductMix_Detail',
        ),
    ]
