# Generated by Django 2.2.7 on 2020-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200622_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='price1',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price2',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price3',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price4',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price5',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامه'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامه'),
        ),
    ]
