# Generated by Django 2.2.7 on 2020-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200622_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='price1',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة سيتم حسابة تلقائي'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price2',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة سيتم حسابة تلقائي'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price3',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة سيتم حسابة تلقائي'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price4',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة سيتم حسابة تلقائي'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='price5',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة فى الخلطة سيتم حسابة تلقائي'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5_count',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الخامة الخامسة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5_price',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر الخامة الخامسة'),
        ),
    ]
