# Generated by Django 2.2.7 on 2020-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200624_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AddField(
            model_name='productmix',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AddField(
            model_name='roll',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تم التحديث :'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
