# Generated by Django 2.2.7 on 2020-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200624_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Roll', verbose_name='إسم الخلطة واللفة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='productmix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductMix', verbose_name=' إسم الخلطة '),
        ),
    ]
