# Generated by Django 2.2.7 on 2020-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200627_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة ')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
