# Generated by Django 2.2.7 on 2020-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20200628_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
