# Generated by Django 2.2.7 on 2020-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200628_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('تخريز', 'تخريز')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
