# Generated by Django 2.2.7 on 2020-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20200701_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('ريسايكل', 'ريسايكل'), ('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
