# Generated by Django 2.2.7 on 2020-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20200702_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('بولى اثلين', 'بولى اثلين'), ('الأوميالين', 'الأوميالين'), ('الصبغة ', 'الصبغة '), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
