# Generated by Django 2.2.7 on 2020-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20200702_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmix',
            name='type1',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الأولى'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type2',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الثانية'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type3',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الثالثة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type4',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الرابعة'),
        ),
        migrations.AlterField(
            model_name='productmix',
            name='type5',
            field=models.CharField(choices=[('تخريز', 'تخريز'), ('الصبغة ', 'الصبغة '), ('الأوميالين', 'الأوميالين'), ('بولى اثلين', 'بولى اثلين'), ('ريسايكل', 'ريسايكل')], max_length=50, verbose_name='إسم الخامة الخامسة'),
        ),
    ]
